import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copy } from "esbuild-plugin-copy";
import { watch } from "fs";
import path from "path";
import { execSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.env.NODE_ENV === "production";
const obsidianPluginPath = process.env.OBSIDIAN_PLUGIN_PATH;

// 自动同步到 Obsidian 插件目录的函数
const syncToObsidian = () => {
	if (obsidianPluginPath) {
		try {
			execSync(`rsync -a packages/obsidian/dist/ "${obsidianPluginPath}"`, { 
				stdio: 'inherit',
				cwd: path.resolve('../..')
			});
			console.log(`🔄 Synced to Obsidian plugin directory: ${obsidianPluginPath}`);
		} catch (error) {
			console.error('❌ Failed to sync to Obsidian:', error.message);
		}
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	plugins: [
		copy({
			// 复制以下资源到 dist/assets 目录
			assets: [
				// 复制插件所需的其他文件到 dist 目录
				{ from: ['./manifest.json'], to: ['./manifest.json'], outDir: './dist' },
				{ from: ['../assets/**/*'], to: ['./assets/'], outDir: './dist' },
				{ from: ['../frontend/dist/**/*'], to: ['./frontend/'], outDir: './dist' },
			],
			verbose: false, // 输出复制操作的日志
		}),
	],
});



if (prod) {
	await context.rebuild();
	syncToObsidian();
	process.exit(0);
} else {
	await context.watch();
	
	// 监听frontend dist目录的变化，触发重新构建
	const frontendDistPath = path.resolve('../frontend/dist');
	console.log(`🔍 Watching frontend dist: ${frontendDistPath}`);
	
	let rebuildTimeout;
	const debounceRebuild = () => {
		clearTimeout(rebuildTimeout);
		rebuildTimeout = setTimeout(async () => {
			try {
				console.log('🔄 Frontend assets changed, rebuilding...');
				await context.rebuild();
				console.log('✅ Rebuild completed');
				syncToObsidian();
			} catch (error) {
				console.error('❌ Rebuild failed:', error);
			}
		}, 100); // 100ms防抖
	};
	
	try {
		watch(frontendDistPath, { recursive: true }, (eventType, filename) => {
			if (filename) {
				console.log(`📁 Frontend file changed: ${filename} (${eventType})`);
				debounceRebuild();
			}
		});
		
		console.log('👀 Watching for changes...');
	} catch (error) {
		console.warn('⚠️ Could not watch frontend dist directory:', error.message);
		console.log('💡 Make sure to run "pnpm dev" in the frontend package first');
	}
}
